<?php


/**
 * This class defines the structure of the 'article' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/05/11 13:37:04
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ArticleTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ArticleTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('article');
		$this->setPhpName('Article');
		$this->setClassname('Article');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		// columns
		$this->addPrimaryKey('ID', 'Id', 'INTEGER', true, null, null);
		$this->addColumn('NOM', 'Nom', 'VARCHAR', false, 255, null);
		$this->addColumn('PRIX', 'Prix', 'FLOAT', false, null, null);
		$this->addColumn('DESCRIPTION', 'Description', 'LONGVARCHAR', false, null, null);
		$this->addColumn('POPULARITE', 'Popularite', 'INTEGER', false, null, null);
		$this->addColumn('STOCK', 'Stock', 'INTEGER', false, null, null);
		$this->addForeignKey('CATEGORIE_ID', 'CategorieId', 'INTEGER', 'categorie', 'ID', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Categorie', 'Categorie', RelationMap::MANY_TO_ONE, array('categorie_id' => 'id', ), null, null);
    $this->addRelation('Commande', 'Commande', RelationMap::ONE_TO_MANY, array('id' => 'article_id', ), null, null);
    $this->addRelation('LigneCommande', 'LigneCommande', RelationMap::ONE_TO_MANY, array('id' => 'article_id', ), null, null);
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ArticleTableMap
