<?php


/**
 * Skeleton subclass for representing a row from the 'ligne_commande' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 01/05/11 12:56:27
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class LigneCommande extends BaseLigneCommande {
    public function __toString(){
        return $this->getArticle()->getNom();
    }
} // LigneCommande
