propel:
  magasin_categorie:
    _attributes: { phpName: Categorie }
    id:
    nom: { type: varchar(255) }
    description: { type: longvarchar }
  magasin_article:
    _attributes: { phpName: Article }
    id:
    nom: { type: varchar(255) }
    prix: { type: float }
    description: { type: longvarchar }
    popularite: { type: integer }
    stock: { type: integer }
    categorie_id:
  magasin_client:
    _attributes: { phpName: Client }
    id:
    nom: { type: varchar(255) }
    prenom: { type: varchar(255) }
    adresse: { type: varchar(255) }
    mail: { type: varchar(255) }
    telephone: { type: varchar(15) }
  magasin_panier:
    _attributes: { phpName: Panier }
    client_id:
    article_id:
    quantite: { type: integer }
  magasin_commande:
    _attributes: { phpName: Commande }
    client_id:
    article_id:
    quantite: { type: integer }
    prix: { type: float }
    created_at:
    etat: { type: varchar(10), default: attente }