generator:
  class: sfPropelGenerator
  param:
    model_class:           Commande
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Commande
    plural:                Commandes
    route_prefix:          commande
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
