<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/01/05 13:29:50

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'DebugPDO',
  'dsn' => 'mysql:dbname=magasin;host=localhost',
  'username' => 'client',
  'password' => 'sesame',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
